### PR TITLE
Updated the parser commands for List, Next, Update and handle majority of bugs

### LINKED ISSUE #183: Create ListParser class
ListParser class used to handle the parsing of user inputs for list command so that the list command class solely handles the execution of the command

### PR DESCRIPTION
**Pull request by antrikshv**
Refactored out the code so that the command class no longer parses any information, instead only executes the command. ListParser, NextParser and UpdateParser, communicate with the user to get all the necessary information first, and possible exceptions before creating the corresponding command class.

Some commands have been updated as such

`list -e` : list overall schedule
`list -t [Event_Index]` : list tasks for specific event 
`list -m` : list the member roster
`list -m e/[Event_Index] t/[Task_Index]` : list members involved in a specific task

`next -e` : next upcoming event
`next -t [Event_Index]` : next upcoming task of a specific event

update commands remains the same.

Lastly, split the switch case statements, depending on whether it was a single word command or multiple word command to allow the usage of single word commands.

Fixes #183 #182 #181 #178 #177 #176 #173 #172 #170 #169 #166 #162 #157 #152 #151 #144 #108

### CODE REVIEW

**Review by crabnuggets — DISMISSED** [review]
Some important points of consideration of the current design of the parsing logic for flags and exception handling.

File: src/main/java/seedu/duke/Duke.java [hunk 1]
```diff
@@ -44,11 +47,14 @@ protected static void runSlam() {
                 System.out.println(feedback.feedbackToUser);
                 Ui.printLineBreak();
             } catch (NullPointerException | NumberFormatException | StringIndexOutOfBoundsException e) {
-                System.out.println("Please key in the commands accurately, use help to view the guide");
+                Ui.printLineBreak();
+                System.out.println("Returning to Main Page...");
```
Comment (crabnuggets) [inline src/main/java/seedu/duke/Duke.java:51]: This `catch` block for this exception is specific to the `update` command but the exceptions thrown might not be unique to that command. As such, would it be better instead to catch these exceptions somewhere within the `UpdateParser` class instead?

File: src/main/java/seedu/duke/commands/updates/UpdateMemberCommand.java [hunk 2]
```diff
@@ -0,0 +1,45 @@
...
+        this.memberToBeAdded = memberToBeAdded;
+        this.memberToBeRemoved = memberToBeRemoved;
+        this.taskToBeUpdated = taskToBeUpdated;
+        this.flag = flag;
+    }
+
+    public CommandResult execute() throws DukeException, InvalidBudgetException {
+        if (flag.equalsIgnoreCase("add")) {
+            addMember(memberToBeAdded);
+        } else if (flag.equalsIgnoreCase("change")) {
```
Comment (crabnuggets) [inline src/main/java/seedu/duke/commands/updates/UpdateMemberCommand.java:28]: A check needs to be performed if the `memberToBeRemoved` is the same as the `memberToBeAdded`.

File: src/main/java/seedu/duke/parser/commandparser/UpdateParser.java [hunk 3]
```diff
@@ -1,11 +1,215 @@
...
+    protected static final String TITLE_FLAG = "title/";
+    protected static final String DATE_FLAG = "date/";
+    protected static final String DEADLINE_FLAG = "deadline/";
+    protected static final String VENUE_FLAG = "venue/";
+    protected static final String BUDGET_FLAG = "budget/";
+    protected static final String DESCRIPTION_FLAG = "description/";
+    protected static final String TASK_FLAG = "task/";
+    protected static final String MEMBER_FLAG = "member/";
+    protected static final String REMOVE_FLAG = "remove/";
+    protected static final String ADD_FLAG = "add";
```
Comment (crabnuggets) [inline src/main/java/seedu/duke/parser/commandparser/UpdateParser.java:32]: I think it would be better to use the flags available in the `ItemAttribute` enum class as quite a few of them are being restated here. Then, the `date` and `deadline` flags can be merged since they both only represent one particular `LocalDateTime` object. Newer flags such as `description`, `task`, `member`, `remove` and `add` can be added to the available enums under the `ItemAttribute` class. 

This would allow access to the inherited `retrieveItemAttribute()` method and standardize the manner in which attributes are parsed in the program.

File: src/main/java/seedu/duke/parser/commandparser/UpdateParser.java [hunk 4]
```diff
@@ -1,11 +1,215 @@
...
+
+    public static Command getUpdateCommand(String commandDetails) {
+        try {
+            int eventIndex = Integer.parseInt(commandDetails) - 1;
+            Event eventToBeUpdated = Duke.eventCatalog.get(eventIndex);
+            Ui.printUpdateEventDetails(eventToBeUpdated);
+            Ui.updateIntroMessage();
+            String userInput = Ui.readInput();
+            String[] userUpdates = userInput.trim().split(">+");
```
Comment (crabnuggets) [inline src/main/java/seedu/duke/parser/commandparser/UpdateParser.java:41]: To clarify, would the `+` in this regex phrase mean that one or more consecutive `>` characters in `userInput` will be matched? If so, what is the intended goal behind this?

File: src/main/java/seedu/duke/parser/commandparser/UpdateParser.java [hunk 5]
```diff
@@ -1,11 +1,215 @@
...
+            Command result = parseUpdateEvent(userUpdates, eventToBeUpdated);
+            Ui.printLineBreak();
+            return result;
+
+        } catch (NumberFormatException e) {
+            System.out.println("Invalid index of event, please type an integer!");
```
Comment (crabnuggets) [inline src/main/java/seedu/duke/parser/commandparser/UpdateParser.java:47]: Other methods that can throw such exceptions such as `changeMember()`, `addMember()` and `removeMember()` that use `Interger.parseInt()` can throw this exception and the incorrect error message would be printed out.

File: src/main/java/seedu/duke/parser/commandparser/UpdateParser.java [hunk 6]
```diff
@@ -1,11 +1,215 @@
...
+            System.out.println("That selection does not exist!");
+        }
         return null;
     }
-}
+
+    private static Command parseUpdateEvent(String[] userUpdates, Event event)
+            throws DukeException, InvalidBudgetException {
+        String[] parsedAttributes = new String[3];
+        LocalDateTime dateTime = null;
```
Comment (crabnuggets) [inline src/main/java/seedu/duke/parser/commandparser/UpdateParser.java:62]: A variable named `dateTimeToUpdate` or something along the same line would aid in code clarity.

File: src/main/java/seedu/duke/parser/commandparser/UpdateParser.java [hunk 7]
```diff
@@ -1,11 +1,215 @@
...
+        double budget = 0;
+        boolean isFlag;
+        for (String update : userUpdates) {
+            isFlag = false;
+            String[] attribute = update.trim().split("/+");
```
Comment (crabnuggets) [inline src/main/java/seedu/duke/parser/commandparser/UpdateParser.java:67]: Similar to the regex phrase in Line 41, unsure of what the idea behind the `+` in this regex is achieving.

File: src/main/java/seedu/duke/parser/commandparser/UpdateParser.java [hunk 8]
```diff
@@ -1,11 +1,215 @@
...
+            if (update.contains(TITLE_FLAG)) {
+                isFlag = true;
+                parsedAttributes[INDEX_OF_TITLE] = attribute[1];
+            }
```
Comment (crabnuggets) [inline src/main/java/seedu/duke/parser/commandparser/UpdateParser.java:71]: On inspection, the current method of identifying flags might lead to inaccurate parsing of user input. For instance, a user might input `adsftitle/asdf` and the conditional check in line 68 will still pass since it looks at the entire string of user input and does a simple check for whether it contains that flag (i.e. position of flag relative to the entire string is not important in the check). Perhaps someone can help verify this as well.

A possible solution would be to use `update.startsWith(XYZ_FLAG)` instead. However, this might require additional methods like `trim()` to be performed on each `update` string first.

It would also be to use the `retrieveItemAttribute()` method from the inherited `Parser` class. This would further unify and standardize the parsing logic for the program in retrieving attributes and also standardize the flags used. That being said, the `retrieveItemAttribute()` method has to also be updated as the current implementation of it has the same issue as well.

File: src/main/java/seedu/duke/parser/commandparser/UpdateParser.java [hunk 9]
```diff
@@ -1,11 +1,215 @@
...
+            if (update.contains(DATE_FLAG)) {
+                isFlag = true;
+                dateTime = Parser.convertDateTime(attribute[1]);
+            }
```
Comment (crabnuggets) [inline src/main/java/seedu/duke/parser/commandparser/UpdateParser.java:75]: Should the other flag checks be checked using an `else if` block (similar to the `parseUpdateTask` method)? Otherwise, it seems like a user input that contains multiple flags that are not separated by `>` can cause some unexpected behavior with the command.

File: src/main/java/seedu/duke/parser/commandparser/UpdateParser.java [hunk 10]
```diff
@@ -1,11 +1,215 @@
...
+        Task taskToBeUpdated = eventToBeUpdated.getFromTaskList(taskNum);
+        String[] userUpdates = prepareTaskUpdates(taskToBeUpdated);
+
+        String[] parsedAttributes = new String[3];
+        LocalDateTime dateTime = null;
+
+        for (String update : userUpdates) {
+            String[] attribute = update.trim().split("/+");
+            if (update.contains(TITLE_FLAG)) {
+                parsedAttributes[INDEX_OF_TITLE] = attribute[1];
```
Comment (crabnuggets) [inline src/main/java/seedu/duke/parser/commandparser/UpdateParser.java:111]: Same comments as the long one regarding lines 68 to 71.

File: src/main/java/seedu/duke/parser/commandparser/UpdateParser.java [hunk 11]
```diff
@@ -1,11 +1,215 @@
...
+            } else if (update.contains(DEADLINE_FLAG)) {
+                dateTime = Parser.convertDateTime(attribute[1]);
+            } else if (update.contains(DESCRIPTION_FLAG)) {
+                parsedAttributes[INDEX_OF_DESCRIPTION] = attribute[1];
+            } else if (update.contains(MEMBER_FLAG)) {
+                attribute[1] = attribute[1].replaceAll("\\s", "");
+                return changeMember(attribute[1], taskToBeUpdated);
```
Comment (crabnuggets) [inline src/main/java/seedu/duke/parser/commandparser/UpdateParser.java:118]: It looks like this regex phrase replaces all whitespace/consecutive whitespaces from the attribute (containing the index of the member) with an empty string. Is there any difference between this and performing a `trim()` operation on the string?

File: src/main/java/seedu/duke/parser/commandparser/UpdateParser.java [hunk 12]
```diff
@@ -1,11 +1,215 @@
...
+    private static Command changeMember(String index, Task taskToBeUpdated) throws DukeException {
+        int memberToBeReplaced = Integer.parseInt(index);
+        int memberIndex = prepareMemberDetails();
+        checkValidMember(memberIndex, taskToBeUpdated);
+        return new UpdateMemberCommand("change", memberIndex, taskToBeUpdated, memberToBeReplaced);
+    }
+
+    private static Command addMember(Task taskToBeUpdated) throws DukeException {
+        int memberIndex = prepareMemberDetails();
+        checkValidMember(memberIndex, taskToBeUpdated);
```
Comment (crabnuggets) [inline src/main/java/seedu/duke/parser/commandparser/UpdateParser.java:140]: Another check might need to be performed to consider the case if the member is already assigned to the task.

File: src/main/java/seedu/duke/parser/commandparser/UpdateParser.java [hunk 13]
```diff
@@ -1,11 +1,215 @@
...
+        int memberIndex = -1;
+        boolean isCorrectMember = false;
+        while (!isCorrectMember) {
+            try {
+                memberIndex = getMemberIndex();
+                isCorrectMember = true;
+            } catch (IndexOutOfBoundsException e) {
+                Ui.printLineBreak();
+                throw new DukeException("This member does not exist. Please enter the index corresponding to "
+                        + "the correct member. ");
```
Comment (crabnuggets) [inline src/main/java/seedu/duke/parser/commandparser/UpdateParser.java:154]: Instead of throwing a `DukeException` here for an `IndexOutOfBoundsExcepton`, catch the `IndexOutOfBoundsException` in the methods (`changeMember()` and `addMember()`) that call it instead?

**Review by crabnuggets — COMMENTED** [review]
Some important points of consideration of the current design of the parsing logic for flags and exception handling.

File: src/main/java/seedu/duke/parser/commandparser/UpdateParser.java (hunk 4 above)
Comment (antrikshv) [reply src/main/java/seedu/duke/parser/commandparser/UpdateParser.java:41]: to ensure that in the instance the user were to key in the key ">" more than once, the program would still be able to obtain the correct command.

File: src/main/java/seedu/duke/parser/commandparser/UpdateParser.java (hunk 7 above)
Comment (antrikshv) [reply src/main/java/seedu/duke/parser/commandparser/UpdateParser.java:67]: to ensure that in the instance the user were to key in the key "/" more than once, the program would still be able to obtain the correct command.

File: src/main/java/seedu/duke/parser/commandparser/UpdateParser.java (hunk 11 above)
Comment (antrikshv) [reply src/main/java/seedu/duke/parser/commandparser/UpdateParser.java:118]: performing a trim(), does not remove the whitespace within a given cell in an index, hence to remove the whitespace, I am required to perform a replace all

File: src/main/java/seedu/duke/parser/commandparser/UpdateParser.java (hunk 5 above)
Comment (antrikshv) [reply src/main/java/seedu/duke/parser/commandparser/UpdateParser.java:47]: Would it be better for me to catch the error in each of the individual classes?

File: src/main/java/seedu/duke/parser/commandparser/UpdateParser.java (hunk 12 above)
Comment (antrikshv) [reply src/main/java/seedu/duke/parser/commandparser/UpdateParser.java:140]: makes sense, will do so!

File: src/main/java/seedu/duke/parser/commandparser/UpdateParser.java (hunk 13 above)
Comment (antrikshv) [reply src/main/java/seedu/duke/parser/commandparser/UpdateParser.java:154]: ok!

File: src/main/java/seedu/duke/commands/Command.java [hunk 14]
```diff
@@ -1,11 +1,14 @@
...
+import seedu.duke.exceptions.DukeException;
+import seedu.duke.exceptions.parserexceptions.InvalidBudgetException;
+
 public class Command {
 
     public Command() {
     }
 
-    public CommandResult execute() {
+    public CommandResult execute() throws DukeException, InvalidBudgetException {
```
[the remark this answers is not in the document]
Comment (antrikshv) [reply src/main/java/seedu/duke/commands/Command.java]: changes have been made!
